// <auto-generated />
using GoatFarm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GoatFarm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GoatFarmDbContext))]
    [Migration("20260708000000_AddMilkWastes")]
    public partial class AddMilkWastes
    {
    }
}
